const db=require('../dbconfiguration/db');
const mongoose = require('mongoose');
const stateMap={
    // 'us':'USA',
    //  'AE':'Armed Services New York',
    //  'AK':'Alaska',
     'AL':'Alabama',
    //  'AP':'Armed Services California',
    //  'AR':'Arkansas',
    //  'AS':'American Samoa',
    //  'AZ':'Arizona',
    //  'BC':'British Columbia',
    //  'CA':'California',
    //  'CO':'Colorado',
    //  'CT':'Connecticut',
    //  'DC':'District of Columbia',
    //  'DE':'Delaware',
    //  'FL':'Florida',
    //  'HI':'Hawaii',
    //  'IA':'Iowa',
    //  'ID':'Idaho',
    //  'IL':'Illinois',
    //  'IN':'Indiana',
    //  'KS':'Kansas',
    //  'LA':'Louisiana',
    //  'LB':'Labrador',
    //  'MA':'Massachusetts',
    //  'MB':'Manitoba',
    //  'MD':'Maryland',
    //  'ME':'Maine',
    //  'MI':'Michigan',
    //  'MN':'Minnesota',
    //  'MP':'Northern Mariana Islands',
    //  'MS':'Mississippi',
    //  'ca':'Canada',
    //  'MT':'Montana',
    //  'NB':'New Brunswick',
    //  'NC':'North Carolina',
    //  'ND':'North Dakota',
    //  'NE':'Nebraska',
     'NJ':'New Jersey',
    //  'NM':'New Mexico',
    //  'NS':'Nova Scotia',
    //  'NV':'Nevada',
     'NY':'New York',
    //  'OH':'Ohio',
    //  'OK':'Oklahoma',
    //  'ON':'Ontario',
    //  'OR':'Oregon',
    //  'PA':'Pennsylvania',
    //  'cy':'Cyprus',
    //  'QC':'Quebec',
    //  'RI':'Rhode Island',
    //  'SC':'South Carolina',
    //  'SD':'South Dakota',
    //  'SK':'Saskatchewan',
    //  'TN':'Tennessee',
     'TX':'Texas',
    //  'UT':'Utah',
    //  'VA':'Virginia',
    //  'VI':'US Virgin Islands',
    //  'VT':'Vermont',
    //  'WA':'Washington',
    //  'WI':'Wisconsin',
    //  'WV':'West Virginia',
    //  'gm':'Germany',
    //  'gy':'Guyana',
    //  'ha':'Haiti',
    //  'ho':'Honduras',
    //  'mx':'Mexico',
    //  'nu':'Nicaragua',
    //  'pn':'Panama',
    //  'ns':'Suriname',
    //  've':'Venezuela'
    };

(async () => {
        const State=db.State;
        for(var states of Object.keys(stateMap)){
            var data=new State({stateCode : states,stateName:stateMap[states]})
            console.log(await data.save());
        }
})()